### ISSUE TITLE
Dynamique include from njk file

### ISSUE THREAD

**Issue by Cezarion** [at0g/nunjucks-loader#40] opened 2016-10-11 23:16 UTC
Hi, 

I'll try to include or import njk template from an another template with variables like that : 
 ```
{% for strate in contents.common[current].strates %}
     <div class="tabs-markets--content">
        {% for i in range(1, 5) -%}
        <div class="tabs-markets--strate">
            {%  include strate %}
        </div>
        {%- endfor %}
    </div>
{% endfor %}
```
where `strate` return a string like `path/to/file.njk`

But I have an error : 

> ERROR in Template render error: (unknown path)
> Template render error: (unknown path)

Without a variable, path (and include) works .. So it's not a path problem.

I think it is related to Webpack's dynamic requirements (https://webpack.github.io/docs/context.html)

Did you or does someone has an idea to make this possible ?

Thank's for help.

**Comment by at0g** [comment] 2016-10-13 14:56
Maybe try adding a context yourself so that all of the possible modules from the dynamic include get bundled into the output?

```
const njkIncludesContext = require.context(process.cwd() + '/src/templates/partials', true, /\.njk$/);
```

Let me know how you go.

**Comment by at0g** [comment] 2016-10-21 01:13
> I think it is related to Webpack's dynamic requirements (https://webpack.github.io/docs/context.html)

Yes, 100%.

**Comment by at0g** [comment] 2016-10-22 13:53
@Cezarion - I'm going to go ahead and close this issue, as it is part of webpack and not a bug with this loader - feel free to reopen if necessary.

**Closed by at0g** 2016-10-22 13:53 UTC
Labels: question, wontfix
